### ISSUE TITLE
文章顶部无法自定义图片

### ISSUE THREAD

**Issue by luanshang** [liuzhihang/halo-theme-hao#547]
在文章的设置内可以添加封面图，却无法添加文章顶部图。在文章中输入如下代码亦无法定义顶部图片
```
---
title: VSCode终端的环境变量与Windows的不同步
categories:
  - VSCode
tags:
  - VSCode
  - 终端
  - Windows
  - Kotlin

top_img:https://test.jpg

halo:
  site: https://luanshang.top/
  name: c12613e7-d882-489b-bf2a-73b532a97fb2
  publish: true
---
```

预期效果如下，此预期效果在Hexo博客中达成
![image](https://github.com/liuzhihang/halo-theme-hao/assets/116410821/f26c9cd3-0565-499e-9896-0639b66fd58b)
