### ISSUE TITLE
prism.js 代码高亮 背景颜色出错

### ISSUE THREAD

**Issue by WekyJay** [liuzhihang/halo-theme-hao#63]
### 是什么版本出现了此问题？

prism.js 代码高亮兼容问题

### 发生了什么？

![image](https://user-images.githubusercontent.com/20734333/215332905-5bfbde49-7968-4743-a30a-a5f839fb6979.png)

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by sun0225SUN** [comment]
此bug已记录，目前可通过在后台注入如下`css`代码修复。
```css
#article-container pre > code {
    background: transparent !important;
}
```
